# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
config.vm.define :balanceador do |balanceador|
    balanceador.vm.box = "debian/bookworm64"
    balanceador.vm.hostname = "balanceador"
    balanceador.vm.network :private_network,
          :libvirt__network_name => "red_privada1",
          :libvirt__dhcp_enabled => false,
          :ip => "10.10.10.1",
          :libvirt__forward_mode => "veryisolated"
    balanceador.vm.provision "shell", run: "always", inline: <<-SHELL
      sysctl -w net.ipv4.ip_forward=1
      iptables -t nat -A POSTROUTING -s 10.10.10.0/24 -j MASQUERADE
    SHELL
  end
  config.vm.define :apache1 do |apache1|
    apache1.vm.box = "debian/bookworm64"
    apache1.vm.hostname = "apache1"
    apache1.vm.network :private_network,
          :libvirt__network_name => "red_privada1",
          :libvirt__dhcp_enabled => false,
          :ip => "10.10.10.11",
          :libvirt__forward_mode => "veryisolated"
    apache1.vm.provision "shell", run: "always", inline: <<-SHELL
        ip r del default
        ip r add default via 10.10.10.1
	      apt-get update && apt-get upgrade -y
	      apt-get install apache2 php libapache2-mod-php -y
        cp /vagrant/ficheros/index1.html /var/www/html/index.html
        cp /vagrant/ficheros/sesion.php /var/www/html/
    SHELL
  end

  config.vm.define :apache2 do |apache2|
    apache2.vm.box = "debian/bookworm64"
    apache2.vm.hostname = "apache2"
    apache2.vm.network :private_network,
          :libvirt__network_name => "red_privada1",
          :libvirt__dhcp_enabled => false,
          :ip => "10.10.10.22",
          :libvirt__forward_mode => "veryisolated"
    apache2.vm.provision "shell", run: "always", inline: <<-SHELL
        ip r del default
        ip r add default via 10.10.10.1
	      apt-get update && apt-get upgrade -y
	      apt-get install apache2 php libapache2-mod-php -y
        cp /vagrant/ficheros/index2.html /var/www/html/index.html
        cp /vagrant/ficheros/sesion.php /var/www/html/
  
	  SHELL
  end
  
end
